export const BOARD_REQUEST = "BOARD_REQUEST"
export const BOARD_REQUEST_GET_SUCCESS = "BOARD_REQUEST_GET_SUCCESS"
export const BOARD_REQUEST_POST_SUCCESS = "BOARD_REQUEST_POST_SUCCESS"
export const BOARD_REQUEST_CREATED_SUCCESS = "BOARD_REQUEST_CREATED_SUCCESS"
export const BOARD_REQUEST_ERROR = "BOARD_REQUEST_SUCCESS"

export const BOARD_DELETE_REQUEST_SUCCESS = "BOARD_DELETE_REQUEST_SUCCESS"
/**
|--------------------------------------------------
| TEAMS
|--------------------------------------------------
*/
export const CREATE_TEAM_REQUEST = 'CREATE_TEAM_REQUEST'
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS'
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS'






export const FETCH_BOARDS = "FETCH_BOARDS"
export const FETCH_BOARD_BY_ID = "FETCH_BOARD_BY_ID"
export const TOGGLE_IS_IMPORTANT_BOARD = "TOGGLE_IS_IMPORTANT_BOARD"
export const CREATE_BOARD_REQUEST = "CREATE_BOARD_REQUEST" 
