export const GET_SCHEMA_CARD = "GET_SCHEMA_CARD"

export const CARD_POST_REQUEST = "CARD_POST_REQUEST"
export const CARD_REQUEST_POST_SUCCESS = "CARD_REQUEST_POST_SUCCESS"

export const CARD_GET_REQUEST_SUCCESSFULL = "CARD_GET_REQUEST_SUCCESSFULL"

export const ADD_LABEL_REQUEST = "ADD_LABEL_REQUEST"
export const ADD_LABEL_REQUEST_SUCCESS = "ADD_LABEL_REQUEST_SUCCESS"