export const GET_SCHEMA_CARD = "GET_SCHEMA_CARD"

export const CARD_POST_REQUEST = "CARD_POST_REQUEST"
export const CARD_REQUEST_POST_SUCCESS = "CARD_REQUEST_POST_SUCCESS"

export const CARD_GET_REQUEST_SUCCESSFULL = "CARD_GET_REQUEST_SUCCESSFULL"

export const ADD_LABEL_REQUEST = "ADD_LABEL_REQUEST"
export const ADD_LABEL_REQUEST_SUCCESS = "ADD_LABEL_REQUEST_SUCCESS"

export const CARD_CREATING_CHECKLIST_REQUEST = "CARD_CREATING_CHECKLIST_REQUEST"
export const CARD_CREATING_CHECKLIST_REQUEST_SUCCESS = "CARD_CREATING_CHECKLIST_REQUEST_SUCCESS"
// is errors not added to the actions
export const CARD_CREATING_CHECKLIST_REQUEST_FAILED = "CARD_CREATING_CHECKLIST_REQUEST_FAILED"

export const CARD_REMOVE_CHECKLIST_REQUEST = "CARD_REMOVE_CHECKLIST_REQUEST"
export const CARD_REMOVE_CHECKLIST_REQUEST_FAILDED = "CARD_REMOVE_CHECKLIST_REQUEST_FAILDED"
export const CARD_REMOVE_CHECKLIST_REQUEST_SUCCESS = "CARD_REMOVE_CHECKLIST_REQUEST_SUCCESS"

export const CARD_ADD_ITEM_TO_CHECKLIST = "CARD_ADD_ITEM_TO_CHECKLIST"
export const CARD_ADD_ITEM_TO_CHECKLIST_SUCCESS = "CARD_ADD_ITEM_TO_CHECKLIST_SUCCESS"
export const CARD_ADD_ITEM_TO_CHECKLIST_FAILED = "CARD_ADD_ITEM_TO_CHECKLIST_FAILED"

export const CARD_CHENCGE_ITEM_FOR_CHECKLIST_REQUEST = "CARD_CHENCGE_ITEM_FOR_CHECKLIST_REQUEST"
export const CARD_CHENCGE_ITEM_FOR_CHECKLIST_REQUEST_SUCCESS = "CARD_CHENCGE_ITEM_FOR_CHECKLIST_REQUEST_SUCCESS"
export const CARD_CHENCGE_ITEM_FOR_CHECKLIST_REQUEST_FAILED = "CARD_CHENCGE_ITEM_FOR_CHECKLIST_REQUEST_FAILED"

export const CARD_UPDATE_CHECKLIST_REQUEST = "CARD_UPDATE_CHECKLIST_REQUEST"
export const CARD_UPDATE_CHECKLIST_REQUEST_SUCCESS = "CARD_UPDATE_CHECKLIST_REQUEST_SUCCESS"
export const CARD_UPDATE_CHECKLIST_REQUEST_FIELD = "CARD_UPDATE_CHECKLIST_REQUEST_FIELD"


export const CARD_UPDATE_REQUEST = "CARD_UPDATE_REQUEST"
export const CARD_UPDATE_SUCCESS = "CARD_UPDATE_SUCCESS"
export const CARD_UPDATE_FAILED = "CARD_UPDATE_FAILED"