export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST"
export const POST_COMMENT_REQUEST_SUCCESS = "POST_COMMENT_REQUEST_SUCCESS"

export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST"
export const GET_COMMENTS_REQUEST_SUCCESS = "GET_COMMENTS_REQUEST_SUCCESS"

export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS"

export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"