export const TOGGLE_EDIT_MODE_BOARDS = "TOGGLE_EDIT_MODE_BOARDS"
export const SETUP_CORDINATES = "SETUP_CORDINATES"

export const TOGGLE_CREATE_BOARD_FORM = "TOGGLE_CREATE_BOARD_FORM"
export const TOGGLE_CREATE_TEAM_FORM = "TOGGLE_CREATE_TEAM_FORM"
export const TOGGLE_CRATIVE_MENU = "TOGGLE_CRATIVE_MENU"
export const TOGGLE_ACCOUNT_SETTINGS_MENU = "TOGGLE_ACCOUNT_SETTINGS_MENU"
export const TOGGLE_LABEL_MENU = "TOGGLE_LABEL_MENU"
export const TOGGLE_ADD_CHECKLIST_FORM = "TOGGLE_ADD_CHECKLIST_FORM"
export const TOGGLE_IS_ALLOW_TO_REMOVE = "TOGGLE_IS_ALLOW_TO_REMOVE"
export const TOGGLE_UPDATE_BOARDNAME_MENU = "TOGGLE_UPDATE_BOARDNAME_MENU"

export const TOGGLE_OVERLAY = "TOGGLE_OVERLAY"

export const SET_SELECTED_ITEM = "SET_SELECTED_ITEM"


export const TOGGLE_SIDEBAR_BOARDLIST = "TOGGLE_SIDEBAR_BOARDLIST"
export const FIX_SIDEBAR = "FIX_SIDEBAR"
export const UNFIX_SIDEBAR = "UNFIX_SIDEBAR"

export const TOGGLE_MENU_BOARD_PAGE = "TOGGLE_MENU_BOARD_PAGE"


export const POPUP_MENU_CLOSE = "POPUP_MENU_CLOSE"