export const TOGGLE_EDIT_MODE_BOARDS = "TOGGLE_EDIT_MODE_BOARDS"
export const SETUP_CORDINATES = "SETUP_CORDINATES"

export const TOGGLE_CREATE_BOARD_FORM = "TOGGLE_CREATE_BOARD_FORM"
export const TOGGLE_CREATE_TEAM_FORM = "TOGGLE_CREATE_TEAM_FORM"
export const TOGGLE_CRATIVE_MENU = "TOGGLE_CRATIVE_MENU"

export const TOGGLE_SIDEBAR_BOARDLIST = "TOGGLE_SIDEBAR_BOARDLIST"
export const FIX_SIDEBAR = "FIX_SIDEBAR"
export const UNFIX_SIDEBAR = "UNFIX_SIDEBAR"
