export const LIST_REQUEST = "LIST_REQUEST"

export const LIST_REQUEST_GET_SUCCESS = "LIST_REQUEST_GET_SUCCESS"

export const LIST_POST_REQUEST = "LIST_POST_REQUEST"
export const LIST_REQUEST_POST_SUCCESS = "LIST_REQUEST_POST_SUCCESS"

export const LIST_GET_SCHEMA = "LIST_GET_SCHEMA"