export const LIST_REQUEST = "LIST_REQUEST"

export const LIST_REQUEST_GET_SUCCESS = "LIST_REQUEST_GET_SUCCESS"

export const LIST_POST_REQUEST = "LIST_POST_REQUEST"
export const LIST_REQUEST_POST_SUCCESS = "LIST_REQUEST_POST_SUCCESS"

export const LIST_GET_SCHEMA = "LIST_GET_SCHEMA"

export const PROJECT_IS_FETCHET_SUCCESSFULLY = "PROJECT_IS_FETCHET_SUCCESSFULLY"
export const CLEAR_PROJECT_DATA = "CLEAR_PROJECT_DATA"

export const LIST_POST_DESCRIPTION_SUCCESS = "LIST_POST_DESCRIPTION_SUCCESS"

export const LIST_UPDATE_REQUEST = "LIST_UPDATE_REQUEST"
export const LIST_UPDATE_REQUEST_SUCCESS = "LIST_UPDATE_REQUEST_SUCCESS"
export const LIST_UPDATE_REQUEST_FAILED = "LIST_UPDATE_REQUEST_FAILED"

