export const USER_REQUEST = "USER_REQUEST"

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_REQUEST_LOGOUT = "USER_REQUEST_LOGOUT"

export const USER_REQUEST_FAILED = "USER_REQUEST_FAILED"

export const USER_UPLOAD_IMAGE_REQUEST = "USER_UPLOAD_IMAGE_REQUEST"
export const USER_UPLOAD_IMAGE_PROGRESS = "USER_UPLOAD_IMAGE_PROGRESS"
export const USER_UPLOAD_IMAGE__SUCCESS = "USER_UPLOAD_IMAGE__SUCCESS"
export const USER_UPLOAD_IMAGE__FAILED = "USER_UPLOAD_IMAGE__FAILED"