export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_ERROR = 'USER_SIGNIN_ERROR'

export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'

